apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-backend-deployment
  labels:
    app: rms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rms-backend
  template:
    metadata:
      labels:
        app: rms-backend
    spec:
      containers:
        - name: rms-backend
          # GitHub Actions에서 이 이미지를 자동으로 업데이트할 것입니다.
          image: kkukku0218/rms-backend:e1418a67422f1bd2296b4e8db5d95cf30f947a2f
          ports:
            - containerPort: 9090
          # DB 연결 정보나 기타 설정이 필요하면 아래 env에 추가하세요.
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "real"
            - name: SPRING_DATASOURCE_USERNAME  # yml의 ${SPRING_DATASOURCE_USERNAME}과 매칭
              valueFrom:
                secretKeyRef:
                  name: rms-db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD  # yml의 ${SPRING_DATASOURCE_PASSWORD}과 매칭
              valueFrom:
                secretKeyRef:
                  name: rms-db-secret
                  key: password
            - name: SPRING_DATASOURCE_URL  # yml의 ${SPRING_DATASOURCE_URL}과 매칭
              valueFrom:
                secretKeyRef:
                  name: rms-db-secret
                  key: url
            - name: APP_SECURITY_CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: rms-db-secret
                  key: cors