apiVersion: v1
kind: Service
metadata:
  name: rms-backend-service
spec:
  type: ClusterIP
  selector:
    app: rms-backend
  ports:
    - port: 9090      # 서비스가 노출할 포트
      targetPort: 9090 # 컨테이너 내부 포트