server:
  port: 9090

spring:
  application:
    name: rms-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/rms
    username: postgres
    password: postgre123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true